### ISSUE TITLE
unable to start music

### ISSUE THREAD

**Issue by Symbiot78** [pathofleastresistor/polr-ytube-media-card#26]
When I search for an artist and press play - nothing happens.
If I start something and nothing happens.. then press pause, then press play music will start playing, but not what I've selected. It will start whatever is already slated for the speaker. 
I use sonos and the speaker is always just in 'paused' state so there's always something ready to play.
so pressing play on a searched artist does noting. Pausing and playing will start my speaker playing something else.

Looking in the logs and I see the following error:

`Logger: homeassistant.core
Source: core.py:2758
First occurred: 09:00:50 (13 occurrences)
Last logged: 09:17:28

Error executing service: <ServiceCall media_player.play_media (c:01HXE3CSXJ1XFZ99BVN030VPVX): entity_id=['media_player.kokken'], extra=metadata=metadataType=3, title=First Time I Met the Blues, artist=Buddy Guy, images=[{'url': 'https://lh3.googleusercontent.com/u08kTWVvl2vD314EiMsdh0gkNbcRD3KR4nnYiLCzxYdZstOynIGZUNV_BsRtk9J5ZiLGkJyNjW7xVyD8Nw=w544-h544-l90-rj'}], media_type=music, media_id=https://rr2---sn-xoxgbphpqu-3g2z.googlevideo.com/videoplayback?expire=1715260620&ei=bHg8ZpCSEvLZ6dsPsMGOoAc&ip=85.191.219.219&id=o-AH6R1tzAR-h2XAaMrMX-bIfNCt2g5RPsOjKDf4nT7zGa&itag=141&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VY&mm=31%2C29&mn=sn-xoxgbphpqu-3g2z%2Csn-4g5lzner&ms=au%2Crdu&mv=m&mvi=2&pl=26&ctier=A&pfa=5&gcr=dk&initcwndbps=2906250&hightc=yes&siu=1&bui=AWRWj2S2xgd-xq9rnSIb4Ps_ukj0MZHRPintQyNIecAojWB_Dkh_e8BUFdfK0273srNZ1ITdPw&spc=UWF9f1c_PrEaJey6mVKfSTQwGVB0Oc-f0MPihgopik6V5U51VO3DY0mrnBZa&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=fYMMCCUdyF2n7zjDIFuPMUYQ&rqh=1&gir=yes&clen=4459904&dur=138.453&lmt=1700181496231932&mt=1715238539&fvip=2&keepalive=yes&c=WEB_REMIX&sefc=1&txp=2318224&n=lmQFhDgBKHFwzkm_tP&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cctier%2Cpfa%2Cgcr%2Chightc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgBjEKQ5SOwI-awfimTGFo8WUaVYMGExVGp5bbn6kBOY8CIBV_QZE7dkCEqXOpZuLaitwdgI4AgUOKvrUQDQ4YA9RA&sig=AJfQdSswRQIhAJHkq-ylVGsIz75HQjNikHOQFpi7Gne5ukh4Dj96Bum0AiAnl6Xj-fgU2zLtRO2Km4z3eRbdymPnarkiIWaeX_42UQ==>
Error executing service: <ServiceCall media_player.play_media (c:01HXE3CZJ1NGB4QE54Q66V85KM): entity_id=['media_player.kokken'], extra=metadata=metadataType=3, title=First Time I Met the Blues, artist=Buddy Guy, images=[{'url': 'https://lh3.googleusercontent.com/u08kTWVvl2vD314EiMsdh0gkNbcRD3KR4nnYiLCzxYdZstOynIGZUNV_BsRtk9J5ZiLGkJyNjW7xVyD8Nw=w544-h544-l90-rj'}], media_type=music, media_id=https://rr2---sn-xoxgbphpqu-3g2z.googlevideo.com/videoplayback?expire=1715260626&ei=cng8ZqPAA4Gv1wKH9bXwBw&ip=85.191.219.219&id=o-ABwCnnsnrzN0kyJhuqghOqV3dJMBq2pnUva6R4tJP9uH&itag=141&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VY&mm=31%2C29&mn=sn-xoxgbphpqu-3g2z%2Csn-4g5lzner&ms=au%2Crdu&mv=m&mvi=2&pl=26&ctier=A&pfa=5&gcr=dk&initcwndbps=3286250&hightc=yes&siu=1&bui=AWRWj2QlUCNjvwEmDyGk8GjxZkMumuDq-Z-OXwd-L4CGAzbMVjSz91iW0ng1e-KkbFCRMb3VDw&spc=UWF9f5R61cv1GMiqw9VwrftPs7hyDNQRmeK2Ieuf5oQTzKyIH3gWuOYpLSrr&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=AtGKQH-ZVlp7h8e8z1PZOOgQ&rqh=1&gir=yes&clen=4459904&dur=138.453&lmt=1700181496231932&mt=1715238776&fvip=2&keepalive=yes&c=WEB_REMIX&sefc=1&txp=2318224&n=CLl-ui0QQ7eu8WHbRZ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cctier%2Cpfa%2Cgcr%2Chightc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgNB_yP7AvBJmmYi5UkL8Zs7tRl7C2FjzwcPePFiH9zRoCIDVA6aet-ltl_N43xkBE5kcSUD3ieblBm7NxOplIytxO&sig=AJfQdSswRAIgddffSK6aeaF4ty8wdvr9127ZmwdIEN_fMshxpfJjYEsCIFHSGSlkxqUi_WeISHWrZ8GtQvP87jy27pCqb4Haq4iU>
Error executing service: <ServiceCall media_player.play_media (c:01HXE3DM4XSPPDXBC9BAXF98DH): entity_id=['media_player.kokken'], extra=metadata=metadataType=3, title=First Time I Met the Blues, artist=Buddy Guy, images=[{'url': 'https://lh3.googleusercontent.com/u08kTWVvl2vD314EiMsdh0gkNbcRD3KR4nnYiLCzxYdZstOynIGZUNV_BsRtk9J5ZiLGkJyNjW7xVyD8Nw=w544-h544-l90-rj'}], media_type=music, media_id=https://rr2---sn-xoxgbphpqu-3g2z.googlevideo.com/videoplayback?expire=1715260647&ei=h3g8ZpX3A6yI6dsPr-aHkAg&ip=85.191.219.219&id=o-AIHFLXrT3fvemLW7s9JNb2NXjCFe15cYIScivHKnHcvK&itag=141&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VY&mm=31%2C29&mn=sn-xoxgbphpqu-3g2z%2Csn-4g5edndz&ms=au%2Crdu&mv=m&mvi=2&pl=26&ctier=A&pfa=5&gcr=dk&initcwndbps=3286250&hightc=yes&siu=1&bui=AWRWj2QO_0Z16HHSC77duUzXGjbJHS0niF7Ba9LWy25DFiHfAhyNWs0xE0AFoqUfVBQwvXIjug&spc=UWF9f35apzuHhEt_dMsbVrpScyNs5LxqNPFxVUG_Xc00H1UF5FpCS8rXtOvR&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=iYDb9Usys6XlBQL9NQp4H7oQ&rqh=1&gir=yes&clen=4459904&dur=138.453&lmt=1700181496231932&mt=1715238776&fvip=1&keepalive=yes&c=WEB_REMIX&sefc=1&txp=2318224&n=KT1LXRA5pVZYODQsq_&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cctier%2Cpfa%2Cgcr%2Chightc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRgIhAMzJHdrgEaGxvyuynKHIa36Lwj_R-gLQ7MIoyrnHN7NvAiEA0KYIjrlZRSgrOSfd_0jMzCQjQ2JySfOE6UIJ7_NX7Us%3D&sig=AJfQdSswRQIhAPnhfxaYyGDC08MrXSVp3TBQsRRXFPOahHwXiFKtevBkAiBQl-dkBzpPV0uLbVqMteYlK01LIGAZG3-R9V4fHOYxqg==>
Error executing service: <ServiceCall media_player.play_media (c:01HXE3DMQFHSYJGHV70D17K4FN): entity_id=['media_player.kokken'], extra=metadata=metadataType=3, title=First Time I Met the Blues, artist=Buddy Guy, images=[{'url': 'https://lh3.googleusercontent.com/u08kTWVvl2vD314EiMsdh0gkNbcRD3KR4nnYiLCzxYdZstOynIGZUNV_BsRtk9J5ZiLGkJyNjW7xVyD8Nw=w544-h544-l90-rj'}], media_type=music, media_id=https://rr2---sn-xoxgbphpqu-3g2z.googlevideo.com/videoplayback?expire=1715260647&ei=h3g8ZsqfLM2vi9oP4d2p8Ac&ip=85.191.219.219&id=o-AIBFNeVo2JTx6-9DhjGxuYwdTdO--CDHglLLbH3cA6VX&itag=141&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VY&mm=31%2C29&mn=sn-xoxgbphpqu-3g2z%2Csn-4g5edndz&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=26&ctier=A&pfa=5&gcr=dk&initcwndbps=2906250&hightc=yes&siu=1&bui=AWRWj2TjTQnSefJb-yBouBQOafZa8AsTdSbTBgLwks-M3xnu3akAhaTqlZyWrJzjDWZGp7eIQQ&spc=UWF9f2wlUBOHgBZOjRvyxhGYfu48j_kcSz1kOEnj_BvwF59U4JnrpTCOhFsz&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=FbNwRFoRDhFx1DyVx0N2CM0Q&rqh=1&gir=yes&clen=4459904&dur=138.453&lmt=1700181496231932&mt=1715238539&fvip=1&keepalive=yes&c=WEB_REMIX&sefc=1&txp=2318224&n=xUyR5kgH0wcQ56WFNf&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cctier%2Cpfa%2Cgcr%2Chightc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgcvLTNbsPE_htoxu9BP1Np4E7ejILNvPYzgV-cv5zOn4CIHolM-cDm3FlxT9iygnga2z3zmTIm6gM3zMFVzS3-uxL&sig=AJfQdSswRQIgOJLeyj-AN0ty07vJiHRd7xuWWjWveeC9RcO1JLw6mKkCIQDurciXNUj56IlWQPYHi8dcjT0qVpxEKZv57lH3afNfjg==>
Error executing service: <ServiceCall media_player.play_media (c:01HXE3DMWYE4CJZAW73C2WAQ6P): entity_id=['media_player.kokken'], extra=metadata=metadataType=3, title=First Time I Met the Blues, artist=Buddy Guy, images=[{'url': 'https://lh3.googleusercontent.com/u08kTWVvl2vD314EiMsdh0gkNbcRD3KR4nnYiLCzxYdZstOynIGZUNV_BsRtk9J5ZiLGkJyNjW7xVyD8Nw=w544-h544-l90-rj'}], media_type=music, media_id=https://rr2---sn-xoxgbphpqu-3g2z.googlevideo.com/videoplayback?expire=1715260647&ei=h3g8ZueYN6ix6dsP1Yq64Ak&ip=85.191.219.219&id=o-AJUC0A2vwux0yNGTEmB6Z5hGiAR5u5JDZhab5Rug4FS1&itag=141&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VY&mm=31%2C29&mn=sn-xoxgbphpqu-3g2z%2Csn-4g5lzner&ms=au%2Crdu&mv=m&mvi=2&pl=26&ctier=A&pfa=5&gcr=dk&initcwndbps=3286250&hightc=yes&siu=1&bui=AWRWj2Qe3_7Ttr8VugMKgkZ9RUIm9Lk7SRGqms6SRfKNH1AxjFd1zQc6SeMnevxadpWehSUaYA&spc=UWF9f4O-PE2_Qm-teZapF8uQdH0AVt-agq1OEq8VKzzRWqBVdAOnftm-rpid&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=ZAjFL0cnrldjK97nzCLUwo4Q&rqh=1&gir=yes&clen=4459904&dur=138.453&lmt=1700181496231932&mt=1715238776&fvip=2&keepalive=yes&c=WEB_REMIX&sefc=1&txp=2318224&n=gJYX4VAkbuBpX9rSjS&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cctier%2Cpfa%2Cgcr%2Chightc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRgIhANXVNEBFSpHAF4zokgc1Lsb8vd9XPzaP7jSWI1u0kl1vAiEApw3QRKcmQSRf9ALbGOvt6saJNraMWR9SzpoUil6C22k%3D&sig=AJfQdSswRQIgPdpra0mRdaOfSzmqbl-YZNYbcW8jMY3FqcHXtCsMa38CIQCgmZtqKehUi0-pKnALcpo9C5-pcHJARFRTELNRLplhmQ==>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sonos/helpers.py", line 63, in wrapper
    result = funct(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 628, in _play_media
    soco.play_uri(media_id, force_radio=is_radio)
  File "/usr/local/lib/python3.12/site-packages/soco/core.py", line 146, in inner_function
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/soco/core.py", line 836, in play_uri
    self.avTransport.SetAVTransportURI(
  File "/usr/local/lib/python3.12/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.12/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 714 received: Illegal MIME-Type from 192.168.1.247

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2758, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 544, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonos/helpers.py", line 77, in wrapper
    raise SonosUpdateError(message) from err
homeassistant.components.sonos.exception.SonosUpdateError: Error calling SonosMediaPlayerEntity._play_media on media_player.kokken: UPnP Error 714 received: Illegal MIME-Type from 192.168.1.247`

**Comment by Symbiot78** [comment]
hmm. . this may be an integration issue.. maybe.. I see this error as well.

`This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:277
integration: yTubeMediaPlayer (documentation, issues)
First occurred: 09:00:48 (14 occurrences)
Last logged: 09:17:28

signature not found, decoding
- self decoded url return 403 status code, attempt 60/60`

**Comment by Artropos** [comment]
@Symbiot78 Sonos doesnt work, you need something to download the song and play it that way, because youtube didnt integrate sonos as spotify did.

you can use a chromecast on your tv to stream it and play it to your sonos
